DB migration script - config.edn still not correct.
I have to figure out how to do that properly - asked on Clojurians slack #duct channel:

[2:36 PM]
jumar I'm trying to setup ragtime migrations in my project - looking at https://github.com/duct-framework/migrator.ragtime. I really don't want to write my sql scripts inside the config.edn file.
There's a mention that URLs are possible:
```Migrations built in this way expect an :up and a :down key that contain vectors of SQL, either as strings, or URLs to resources on the classpath.
```

However, I'm having a hard time to figure out how to do that.
I've tried this:
``` :duct.migrator/ragtime
 {:migrations [#ig/ref :my-app.migrations/init]}

 [:duct.migrator.ragtime/sql :my-app.migrations/init]
 {:up ["migrations/2018-13-03-init.sql"]
  :down []}

```
but got sql exception:
```Caused by org.postgresql.util.PSQLException
   ERROR: syntax error at or near "migrations" Position: 1

```
How people usually do that?
I can't imagine that putting all those scripts into a config is a manageable way to do that...
Ideally, I'd like to just configure the directory that contains all db migration scripts and everything else will be handled automatically without any need to always add a new config when new migration script is added.